[package]
name = "mirage"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies]
libloading = "0.3.1"

[dependencies.mirage-high]
path = "high"
version = "0.1.0"